/*
-- Query: SELECT * FROM shashank.ques1
LIMIT 0, 1000

-- Date: 2017-08-09 13:34
*/
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (1,'Who is the mother of load Ram?','Kausalya','Kaikeyi','Sumitra','Sita','Kausalya','Kausalya');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (2,'What is the capital of India?','Lucknow','new delhi','Bombay','Tamil Nadu','new delhi','new delhi');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (3,'What is the full form of ISRO?','Indian Satellite Research Organization','Indian Space Reseach Organization','International Solar Research  Organization','International Satellite Research Organization','Indian Space Reseach Organization','Indian Space Reseach Organization');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (4,'How much payload consist in the mars orbit mission?','10kg','100kg','55kg','15kg','15kg','15kg');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (5,'What is the full  form of PSLV?','Polar Solar Launch Vehicle','Planetary Satellite Launch Vehicle','Polar Statellite Launch Vehicle ','Primary Solar Launch Vehicle','Polar Statellite Launch Vehicle ','Polar Statellite Launch Vehicle ');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (6,'When did demonetization occur in India?','on 8th nov 2016 at 20:00 hrs','on 01st march 2017 at 20:00 hrs','on 1st janaury 2017 at 12:00 hrs','on 31 march 2016 at 23:00 hrs','on 8th nov 2016 at 20:00 hrs','on 8th nov 2016 at 20:00 hrs');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (7,' What sport used the term ‘home run’ long before baseball?','Archery','Boxing','Cricket','Basketball','Cricket',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (8,'What number lies between 5 and 9 on a British dart board?','13','7','14','12','12','12');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (9,'Kareem Abdul-Jabbar played 20 seasons in which sport?','Boxing','Cricket','Basketball','Chess','Basketball','Basketball');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (10,'The language spoken by the people by Pakistan is ?','Hindi','Palauan','Nauruan','Sindhi','Sindhi','Sindhi');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (11,'Country that has the highest in Barley Production ?','Russia','India','France','China','Russia','Russia');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (12,'The Central Rice Research Station is situated in ?','Chennai','Cuttak','Bangalore','Quilon','Cuttak','Cuttak');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (13,'The first ruler of Pala dynasty was ?','Gopala','Bhaskaravarman','Dharmapala','None of these','Gopala',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (14,'Who is the first woman to successfully climb K2, the world’s second highest mountain peak?','Junko Tabei  ','Tamae Watanabe ','Wanda Rutkiewicz ','CHantal Mauduit','Wanda Rutkiewicz ','Wanda Rutkiewicz ');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (15,'The oldest written plan of government in effect is in which country? ','Pakistan','The United States of America','Iran','Sri Lanka','The United States of America','The United States of America');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (16,'In sport, what is black, 1 inch thick, 3 inches in diameter, and weighs between 5.5 and 6 ounces?','Football','Ice Hockey Puck','Cricket','Hockey','Ice Hockey Puck',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (17,'Indian Navy Act was passed on ?','1930','1925','1927','1901','1927','1927');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (18,' The Tydings–McDuffie Act is passed, allowing the Philippines a greater degree of self-government from whom?','India','Ukrain','Pakistan','The United States','The United States','The United States');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (19,'The first to establish regular trade with India was ?','Portuguese','English','Dutch','French','Portuguese',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (20,'. August 9 1925 is known in the Indian History for which of the following incidences?',' Chauri Chaura incidence','Kakori Train Robbery','The seize of Cawnpore','Jallianwallah Bagh Incidence','Kakori Train Robbery','Kakori Train Robbery');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (21,' In which year Jahangir issued the charter to East India Company for establishing the trade establishments in India?','1615','1668','1625','1617','1617','1617');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (22,'Who wrote ‘Animal Farm’?','George Orwell','Louisa May Alcott ','Mitch Albom',' Isabella Macdonald Alden','George Orwell',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (23,'Which U.S President was assassinated in 1865?',' Bill Clinton',' Calvin Coolidge','Abraham Lincoln','Harry S. Truman','Abraham Lincoln','Abraham Lincoln');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (24,'True caviar is the roe of which type of fish?','Salmon','Sturgeon','Steelhead trout','Star fish','Sturgeon','Sturgeon');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (25,'What is the fear of clowns called?','Acrophobia','Germanophile','Polonism','Coulrophobia','Coulrophobia',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (26,'Among whom does the Indian Constitution permit to take part in the Proceedings of Parliament?','Solicitor General ','Attorney General','Cabinet Secretary','Cheif Justic','Attorney General','Attorney General');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (27,'Who commanded the ‘Hector’, the first British trading ship to land at Surat?','William Hawkins ','Paul Canning ','Thomas Roe  ','James Lancaster','William Hawkins ','William Hawkins ');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (28,'Which poem are these lines from: ''Nari tum keval Shraddha ho, Vishwas-rajat-nag- pagtal mein, Piyush-srot-si baha karo, Jivan ke sunder samtal hein''?','Prem Pathek','Kaanan Kusum','Aansu','Kamayani','Kamayani',NULL);
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (29,'The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.','Publius','John G. Roberts','John Roberts','Isabella','Publius','Publius');
INSERT INTO `ques1` (`qid`,`quesname`,`opta`,`optb`,`optc`,`optd`,`crrtans`,`userans`) VALUES (30,'Which colonial power ended its involvement in India by selling the rights of the Nicobar Islands to the British on October 18, 1868?','France','Italy','Belgium ','Denmark','Denmark','Denmark');
